serviceMonitor:
  enabled: true
  interval: 30s
service:
  type: ClusterIP
nodeSelector:
  kubernetes.io/os: linux
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

